version: '3.8'

services:
  deepsearch:
    build: .
    container_name: deepsearch
    ports:
      - "8000:8000"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE:-http://localhost:8080/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./models:/models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Optional Redis cache for production
  # redis:
  #   image: redis:alpine
  #   container_name: deepsearch-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped

# volumes:
#   redis-data:
